{
  "id": "capture",
  "version": "0.1",
  "title": "Capture Logs",
  "components": {
    "docs": [
      {
        "id": "capture.guide",
        "path": "docs/guides/capture.md",
        "tags": ["capture", "logging", "workflow"]
      }
    ],
    "prompts": [
      {
        "id": "capture.start",
        "text": "start capture logging",
        "workflow_id": "capture.start"
      },
      {
        "id": "capture.show",
        "text": "show capture log",
        "workflow_id": "capture.show"
      },
      {
        "id": "capture.clear",
        "text": "clear capture log",
        "workflow_id": "capture.clear"
      }
    ],
    "workflows": [
      {
        "id": "capture.start",
        "title": "Start capture",
        "steps": [
          {
            "id": "capture.start",
            "command": "dev.kit capture start",
            "note": "Starts full capture shell by default.",
            "runnable": false
          }
        ],
        "response": {
          "instructions": [
            "Start capture before running commands you want reviewed.",
            "Use --input if you only need command history."
          ],
          "normalized": "Use dev.kit capture start to record commands and output for review."
        }
      },
      {
        "id": "capture.show",
        "title": "Show capture log",
        "steps": [
          {
            "id": "capture.show",
            "command": "dev.kit capture show",
            "note": "Tails the log file.",
            "runnable": false
          }
        ],
        "response": {
          "instructions": [
            "Review the log, then clear it if needed."
          ],
          "normalized": "Use dev.kit capture show to view the latest captured commands."
        }
      },
      {
        "id": "capture.clear",
        "title": "Clear capture log",
        "edge_cases": [
          "Use --force to skip confirmation."
        ],
        "steps": [
          {
            "id": "capture.clear",
            "command": "dev.kit capture clear",
            "note": "Clears the capture log.",
            "runnable": false,
            "protected": true,
            "preview": "Review the log before clearing."
          }
        ],
        "response": {
          "instructions": [
            "Clear the capture log after review to keep iterations clean."
          ],
          "normalized": "Use dev.kit capture clear to remove the current capture log."
        }
      }
    ]
  }
}
