kind: archetypeSignals
version: udx.io/dev.kit/v1

config:
  wordpress_files:
    - wp-config.php
  wordpress_dirs:
    - wp-content
    - wp-content/plugins
    - wp-content/themes
    - wp-content/mu-plugins
  kubernetes_files:
    - Chart.yaml
    - helmfile.yaml
  kubernetes_globs:
    - charts/*/Chart.yaml
    - k8s/*.yaml
    - k8s/*.yml
    - k8s/**/*.yaml
    - k8s/**/*.yml
  kubernetes_dirs:
    - k8s
    - charts
    - helm
  terraform_files:
    - main.tf
    - variables.tf
  terraform_dirs:
    - terraform
  terraform_globs:
    - terraform/*.tf
    - terraform/**/*.tf
    - "*.tf"
  workflow_primary_dirs:
    - .github/workflows
