#!/usr/bin/env bash

# @description: Start an agent session with full repo context

dev_kit_cmd_agent() {
  local format="${1:-text}"
  local repo_dir="${2:-$(pwd)}"

  local repo_root repo_name context_yaml_path agents_md_path
  repo_root="$(dev_kit_repo_root "$repo_dir")"
  repo_dir="${repo_root:-$repo_dir}"
  repo_name="$(dev_kit_repo_name "$repo_dir")"
  context_yaml_path="$(dev_kit_context_yaml_path "$repo_dir")"
  agents_md_path="${repo_dir}/AGENTS.md"

  if [ ! -f "$context_yaml_path" ]; then
    if [ "$format" = "json" ]; then
      printf '{ "error": "context not found", "hint": "run dev.kit repo first", "path": "%s" }\n' \
        "$(dev_kit_json_escape "$context_yaml_path")"
    else
      dev_kit_output_title "dev.kit agent"
      dev_kit_output_section "error"
      dev_kit_output_list_item "Context not found — run dev.kit repo first."
    fi
    return 1
  fi

  dev_kit_agent_write_agents_md "$repo_dir" "$agents_md_path"

  local archetype profile
  archetype="$(dev_kit_repo_primary_archetype "$repo_dir")"
  profile="$(dev_kit_repo_primary_profile "$repo_dir")"

  if [ "$format" = "json" ]; then
    dev_kit_template_render "agent.json" \
      "command=agent" \
      "repo=$(dev_kit_json_escape "$repo_name")" \
      "path=$(dev_kit_json_escape "$repo_dir")" \
      "archetype=$(dev_kit_json_escape "$archetype")" \
      "profile=$(dev_kit_json_escape "$profile")" \
      "agents_md=$(dev_kit_json_escape "$agents_md_path")" \
      "context=$(dev_kit_json_escape "$context_yaml_path")" \
      "priority_refs=$(dev_kit_repo_priority_refs_json "$repo_dir")" \
      "entrypoints=$(dev_kit_repo_entrypoints_json "$repo_dir")" \
      "workflow_contract=$(dev_kit_repo_workflow_json "$repo_dir")" \
      "factors=$(dev_kit_repo_factor_summary_json "$repo_dir")" \
      "task="
    return 0
  fi

  dev_kit_output_title "dev.kit agent"
  dev_kit_output_summary "${repo_name} • ${archetype}"
  dev_kit_output_section "context"
  dev_kit_output_list_item "context:   ${context_yaml_path}"
  dev_kit_output_list_item "agents.md: ${agents_md_path}"
  dev_kit_output_section "start session with"
  dev_kit_output_list_item "Following AGENTS.md context and repo workflow, [your task here]"
}

# Write AGENTS.md — inlines key context from context.yaml so agents have
# everything they need without following a pointer to another file.
dev_kit_agent_write_agents_md() {
  local repo_dir="$1"
  local agents_md_path="$2"
  local context_yaml="${repo_dir}/.rabbit/context.yaml"

  {
    printf '# AGENTS.md\n\n'
    printf '_Auto-generated by `dev.kit agent`. Run `dev.kit repo` then `dev.kit agent` to refresh._\n\n'
    printf '**This file contains the full repo context. Do not use find, ls, glob, or directory scans to explore the repository. If you need more detail, read only the files listed in Priority refs below.**\n\n'

    if [ ! -f "$context_yaml" ]; then
      printf 'Run `dev.kit repo` to generate context.\n'
    else
      # ── repo identity ────────────────────────────────────────────────────────
      local _name _arch _profile
      _name="$(awk    '/^repo:/{f=1} f && /^  name:/     {sub(/.*name:[[:space:]]*/,""); print; exit}' "$context_yaml")"
      _arch="$(awk    '/^repo:/{f=1} f && /^  archetype:/{sub(/.*archetype:[[:space:]]*/,""); print; exit}' "$context_yaml")"
      _profile="$(awk '/^repo:/{f=1} f && /^  profile:/  {sub(/.*profile:[[:space:]]*/,""); print; exit}' "$context_yaml")"
      printf '## Repo: %s\n\n' "${_name:-unknown}"
      [ -n "$_arch" ]    && printf -- '- archetype: %s\n' "$_arch"
      [ -n "$_profile" ] && printf -- '- profile: %s\n' "$_profile"
      printf '\n'

      # ── commands ─────────────────────────────────────────────────────────────
      local _cmds
      _cmds="$(awk '/^commands:/{f=1;next} f && /^[a-zA-Z#]/{f=0} f' "$context_yaml")"
      if [ -n "$_cmds" ]; then
        printf '## Commands\n\n```\n%s\n```\n\n' "$_cmds"
      fi

      # ── gaps (actionable next steps) ─────────────────────────────────────────
      local _gaps
      _gaps="$(awk '/^gaps:/{f=1;next} f && /^[a-zA-Z#]/{f=0} f && /^  - /' "$context_yaml")"
      if [ -n "$_gaps" ]; then
        printf '## Gaps\n\n%s\n\n' "$_gaps"
      fi

      # ── priority refs ────────────────────────────────────────────────────────
      local _refs
      _refs="$(awk '/^refs:/{f=1;next} f && /^[a-zA-Z#]/{f=0} f && /^  - /' "$context_yaml")"
      if [ -n "$_refs" ]; then
        printf '## Priority refs\n\n%s\n\n' "$_refs"
      fi

      # ── engineering practices (all, inlined) ──────────────────────────────────
      local _practices
      _practices="$(awk '/^practices:/{f=1;next} f && /^[a-zA-Z#]/{f=0} f && /^  - /' "$context_yaml")"
      if [ -n "$_practices" ]; then
        printf '## Engineering practices\n\n%s\n\n' "$_practices"
      fi

      # ── workflow (first 5 steps) ──────────────────────────────────────────────
      local _workflow
      _workflow="$(awk '/^workflow:/{f=1;next} f && /^[a-zA-Z#]/{f=0} f && /^  - /' "$context_yaml" | head -5)"
      if [ -n "$_workflow" ]; then
        printf '## Workflow\n\n%s\n\n' "$_workflow"
        printf '_Full workflow in `.rabbit/context.yaml`_\n\n'
      fi

      # ── lessons ───────────────────────────────────────────────────────────────
      local _lessons
      _lessons="$(awk '/^lessons:/{f=1;next} f && /^[a-zA-Z#]/{f=0} f && /^  - /' "$context_yaml")"
      if [ -n "$_lessons" ]; then
        printf '## Lessons from prior sessions\n\n%s\n\n' "$_lessons"
      fi
    fi
  } > "$agents_md_path"
}
