#!/usr/bin/env bash

# @description: Start an agent session with full repo context

dev_kit_cmd_agent() {
  local format="${1:-text}"
  local repo_dir="${2:-$(pwd)}"

  local repo_root repo_name context_yaml_path agents_md_path
  repo_root="$(dev_kit_repo_root "$repo_dir")"
  repo_dir="${repo_root:-$repo_dir}"
  repo_name="$(dev_kit_repo_name "$repo_dir")"
  context_yaml_path="$(dev_kit_context_yaml_path "$repo_dir")"
  agents_md_path="${repo_dir}/AGENTS.md"

  # Print title early so spinner output has context
  [ "$format" = "text" ] && dev_kit_output_title "dev.kit agent"

  # Auto-generate context if missing — no manual repo step required
  if [ ! -f "$context_yaml_path" ]; then
    [ "$format" = "text" ] && dev_kit_spinner_start "generating repo context"
    dev_kit_context_yaml_write "$repo_dir" >/dev/null
    [ "$format" = "text" ] && dev_kit_spinner_stop "context ready"
  fi

  # If generation still failed, report error
  if [ ! -f "$context_yaml_path" ]; then
    if [ "$format" = "json" ]; then
      printf '{ "error": "context generation failed", "path": "%s" }\n' \
        "$(dev_kit_json_escape "$context_yaml_path")"
    else
      dev_kit_output_section "error"
      dev_kit_output_list_item "Context generation failed — check repo at ${repo_dir}"
    fi
    return 1
  fi

  dev_kit_agent_write_agents_md "$repo_dir" "$agents_md_path"

  local archetype profile
  archetype="$(dev_kit_repo_primary_archetype "$repo_dir")"
  profile="$(dev_kit_repo_primary_profile "$repo_dir")"

  if [ "$format" = "json" ]; then
    dev_kit_template_render "agent.json" \
      "command=agent" \
      "repo=$(dev_kit_json_escape "$repo_name")" \
      "path=$(dev_kit_json_escape "$repo_dir")" \
      "archetype=$(dev_kit_json_escape "$archetype")" \
      "profile=$(dev_kit_json_escape "$profile")" \
      "agents_md=$(dev_kit_json_escape "$agents_md_path")" \
      "context=$(dev_kit_json_escape "$context_yaml_path")" \
      "priority_refs=$(dev_kit_repo_priority_refs_json "$repo_dir")" \
      "entrypoints=$(dev_kit_repo_entrypoints_json "$repo_dir")" \
      "workflow_contract=$(dev_kit_repo_workflow_json "$repo_dir")" \
      "factors=$(dev_kit_repo_factor_summary_json "$repo_dir")" \
      "task="
    return 0
  fi

  dev_kit_output_summary "${repo_name} • ${archetype} • profile ${profile}"

  # Key entrypoints — devs and agents see what commands are available
  local ep_json verify_cmd build_cmd run_cmd
  ep_json="$(dev_kit_repo_entrypoints_json "$repo_dir")"
  verify_cmd="$(printf '%s' "$ep_json" | jq -r '.verify // empty' 2>/dev/null)"
  build_cmd="$(printf '%s' "$ep_json" | jq -r '.build // empty' 2>/dev/null)"
  run_cmd="$(printf '%s' "$ep_json" | jq -r '.run // empty' 2>/dev/null)"
  if [ -n "$verify_cmd" ] || [ -n "$build_cmd" ] || [ -n "$run_cmd" ]; then
    dev_kit_output_section "commands"
    [ -n "$verify_cmd" ] && dev_kit_output_row "verify" "$verify_cmd"
    [ -n "$build_cmd" ]  && dev_kit_output_row "build"  "$build_cmd"
    [ -n "$run_cmd" ]    && dev_kit_output_row "run"    "$run_cmd"
  fi

  dev_kit_output_section "context"
  dev_kit_output_row "agents.md" "$agents_md_path"
  dev_kit_output_row "context.yaml" "$context_yaml_path"

  dev_kit_output_section "start session with"
  dev_kit_output_list_item "Following AGENTS.md context and repo workflow, [your task here]"

  dev_kit_output_section "next"
  dev_kit_output_row "refresh context" "dev.kit repo"
  dev_kit_output_row "session lessons" "dev.kit learn"
}

# Write AGENTS.md — inlines full context from context.yaml so agents have
# everything they need without scanning the filesystem.
dev_kit_agent_write_agents_md() {
  local repo_dir="$1"
  local agents_md_path="$2"
  local context_yaml="${repo_dir}/.rabbit/context.yaml"

  {
    printf '# AGENTS.md\n\n'
    printf '_Auto-generated by `dev.kit agent`. Source of truth: `.rabbit/context.yaml`._\n\n'

    if [ ! -f "$context_yaml" ]; then
      printf 'Run `dev.kit repo` to generate context.\n'
    else
      # ── Rules — anti-drift, anti-scanning ────────────────────────────────────
      printf '## Rules\n\n'
      printf '1. **Do NOT scan the filesystem.** No `find`, `ls -R`, `glob`, or recursive directory walks. All paths you need are listed in this file.\n'
      printf '2. **Read only files listed in Priority refs and Config manifests.** If a file is not listed, do not read it unless a listed file explicitly references it.\n'
      printf '3. **Verify locally before committing.** Run the verify command below before reporting work as done. Do not skip this step.\n'
      printf '4. **Follow the Workflow below as your execution contract.** Do not invent ad hoc steps or skip workflow phases.\n'
      printf '5. **Use config manifests as traceable dependencies.** When you need to understand how something works, check the YAML manifest that defines it — not the code that reads it.\n\n'

      # ── repo identity ────────────────────────────────────────────────────────
      local _name _arch _profile
      _name="$(awk    '/^repo:/{f=1} f && /^  name:/     {sub(/.*name:[[:space:]]*/,""); print; exit}' "$context_yaml")"
      _arch="$(awk    '/^repo:/{f=1} f && /^  archetype:/{sub(/.*archetype:[[:space:]]*/,""); print; exit}' "$context_yaml")"
      _profile="$(awk '/^repo:/{f=1} f && /^  profile:/  {sub(/.*profile:[[:space:]]*/,""); print; exit}' "$context_yaml")"
      printf '## Repo: %s\n\n' "${_name:-unknown}"
      [ -n "$_arch" ]    && printf -- '- archetype: %s\n' "$_arch"
      [ -n "$_profile" ] && printf -- '- profile: %s\n' "$_profile"
      printf '\n'

      # ── commands ─────────────────────────────────────────────────────────────
      local _cmds
      _cmds="$(awk '/^commands:/{f=1;next} f && /^[a-zA-Z#]/{f=0} f' "$context_yaml")"
      if [ -n "$_cmds" ]; then
        printf '## Commands\n\n```\n%s\n```\n\n' "$_cmds"
      fi

      # ── priority refs ────────────────────────────────────────────────────────
      local _refs
      _refs="$(awk '/^refs:/{f=1;next} f && /^[a-zA-Z#]/{f=0} f && /^  - /' "$context_yaml")"
      if [ -n "$_refs" ]; then
        printf '## Priority refs\n\n'
        printf 'Read these for full context. Do not explore beyond them.\n\n'
        printf '%s\n\n' "$_refs"
      fi

      # ── config manifests ─────────────────────────────────────────────────────
      local _manifests
      _manifests="$(awk '/^manifests:/{f=1;next} f && /^[a-zA-Z#]/{f=0} f && /^  - /' "$context_yaml")"
      if [ -n "$_manifests" ]; then
        printf '## Config manifests\n\n'
        printf 'These YAML files define the project workflow, tooling, and behavior. Trace dependencies here before reading shell code.\n\n'
        printf '%s\n\n' "$_manifests"
      fi

      # ── gaps (actionable next steps) ─────────────────────────────────────────
      local _gaps
      _gaps="$(awk '/^gaps:/{f=1;next} f && /^[a-zA-Z#]/{f=0} f && /^  - /' "$context_yaml")"
      if [ -n "$_gaps" ]; then
        printf '## Gaps\n\n%s\n\n' "$_gaps"
      fi

      # ── workflow (full, with operational notes) ──────────────────────────────
      local _workflow
      _workflow="$(awk '/^workflow:/{f=1;next} f && /^[a-zA-Z#]/{f=0} f && /^  - /' "$context_yaml")"
      if [ -n "$_workflow" ]; then
        printf '## Workflow\n\n'
        printf 'Follow these steps in order. Steps with notes contain operational guidance — read them.\n\n'
        printf '%s\n\n' "$_workflow"
      fi

      # ── engineering practices ────────────────────────────────────────────────
      local _practices
      _practices="$(awk '/^practices:/{f=1;next} f && /^[a-zA-Z#]/{f=0} f && /^  - /' "$context_yaml")"
      if [ -n "$_practices" ]; then
        printf '## Engineering practices\n\n%s\n\n' "$_practices"
      fi

      # ── lessons ───────────────────────────────────────────────────────────────
      local _lessons
      _lessons="$(awk '/^lessons:/{f=1;next} f && /^[a-zA-Z#]/{f=0} f && /^  - /' "$context_yaml")"
      if [ -n "$_lessons" ]; then
        printf '## Lessons from prior sessions\n\n'
        printf 'Read these before starting work. They contain workflow rules and operational patterns learned from real agent sessions.\n\n'
        printf '%s\n\n' "$_lessons"
      fi
    fi
  } > "$agents_md_path"
}
