#!/usr/bin/env bash

# @description: Start an agent session with full repo context

dev_kit_cmd_agent() {
  local format="${1:-text}"
  local repo_dir="${2:-$(pwd)}"

  local repo_root repo_name manifest_path agents_md_path
  repo_root="$(dev_kit_repo_root "$repo_dir")"
  repo_dir="${repo_root:-$repo_dir}"
  repo_name="$(dev_kit_repo_name "$repo_dir")"
  manifest_path="$(dev_kit_scaffold_manifest_path "$repo_dir")"
  agents_md_path="${repo_dir}/AGENTS.md"

  if [ ! -f "$manifest_path" ]; then
    if [ "$format" = "json" ]; then
      printf '{ "error": "manifest not found", "hint": "run dev.kit repo first", "path": "%s" }\n' \
        "$(dev_kit_json_escape "$manifest_path")"
    else
      dev_kit_output_title "dev.kit agent"
      dev_kit_output_section "error"
      dev_kit_output_list_item "Manifest not found — run dev.kit repo first."
    fi
    return 1
  fi

  # Generate AGENTS.md only if dev.kit repo hasn't already done it
  if [ ! -f "$agents_md_path" ]; then
    dev_kit_agent_write_agents_md "$manifest_path" "$agents_md_path"
  fi

  local archetype profile
  archetype="$(jq -r '.archetype // empty' "$manifest_path" 2>/dev/null)"
  profile="$(jq -r '.profile   // empty' "$manifest_path" 2>/dev/null)"

  if [ "$format" = "json" ]; then
    dev_kit_template_render "agent.json" \
      "command=agent" \
      "repo=$(dev_kit_json_escape "$repo_name")" \
      "path=$(dev_kit_json_escape "$repo_dir")" \
      "archetype=$(dev_kit_json_escape "$archetype")" \
      "profile=$(dev_kit_json_escape "$profile")" \
      "agents_md=$(dev_kit_json_escape "$agents_md_path")" \
      "manifest=$(dev_kit_json_escape "$manifest_path")" \
      "priority_refs=$(jq -c '.priority_refs    // []' "$manifest_path" 2>/dev/null)" \
      "entrypoints=$(jq -c '.entrypoints        // {}' "$manifest_path" 2>/dev/null)" \
      "workflow_contract=$(jq -c '.workflow_contract // []' "$manifest_path" 2>/dev/null)" \
      "factors=$(jq -c '.factors              // {}' "$manifest_path" 2>/dev/null)" \
      "task="
    return 0
  fi

  dev_kit_output_title "dev.kit agent"
  dev_kit_output_summary "${repo_name} • ${archetype}"
  dev_kit_output_section "context"
  dev_kit_output_list_item "manifest:  ${manifest_path}"
  dev_kit_output_list_item "agents.md: ${agents_md_path}"
}

# Write AGENTS.md from manifest — called by dev.kit repo (and agent as fallback)
dev_kit_agent_write_agents_md() {
  local manifest_path="$1"
  local agents_md_path="$2"

  {
    printf '# AGENTS.md\n\n'
    printf '> Generated by dev.kit. Do not edit manually — run `dev.kit repo` to refresh.\n\n'

    printf '## Repo\n\n'
    jq -r '"- **Name**: \(.repo)\n- **Archetype**: \(.archetype)\n- **Profile**: \(.profile)"' \
      "$manifest_path" 2>/dev/null
    printf '\n\n'

    printf '## Read first\n\n'
    jq -r '.priority_refs[]? | "- \(.)"' "$manifest_path" 2>/dev/null | head -6
    printf '\n'

    printf '## Entrypoints\n\n'
    jq -r '.entrypoints | to_entries[] | select(.value != null) | "- **\(.key)**: `\(.value)`"' \
      "$manifest_path" 2>/dev/null
    printf '\n'
  } > "$agents_md_path"
}
